#!/usr/bin/env python
# _*_ coding:utf-8 _*_
import RPi.GPIO as GPIO
import threading
import time



class led_red(threading.Thread):  
    def __init__(self, threadID, name, counter):
        threading.Thread.__init__(self)
        self.threadID = threadID
        self.name = name
        self.counter = counter

    def run(self):  
        print "Starting " + self.name
        led_red_on()
        print "Exiting " + self.name

def led_red_on():
    GPIO.setmode(GPIO.BCM)
    GPIO.setup(26, GPIO.OUT)
    GPIO.output(26, GPIO.HIGH)


def turnRedOn():
    # 创建新线程
    thread1 = led_red(1, "LED:Red", 1)
    # 开启线程
    thread1.start()
    time.sleep(0.5)
    GPIO.cleanup()



turnRedOn()
